name: ameen_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  drop_shadow_image: ^0.9.0
   

flutter_icons:
  android: "launchr_icons"
  ios: true
  image_path: "asset/images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/